/**
 * Text generated for a compiled `Stepper` node: the Layer 2 `mat-stepper`
 * template, the component source edits, and the stylesheet.
 *
 * @internal
 */
import { SchematicsException } from '@angular-devkit/schematics';

import { templateSectionMarkers } from '../embed-component/index';
import type { StepAstOptions, StepperAstOptions } from './ast';

/** Template section that hosts the children of one step slot (`header`, `children`, `actions`). */
export function stepSection(step: Pick<StepAstOptions, 'name'>, slot: string): string {
  return `step-${step.name}-${slot}`;
}

/** Escape a value for a double-quoted Angular template attribute. */
function escapeAttributeText(value: string): string {
  const entities: Record<string, string> = {
    '&': '&amp;',
    '<': '&lt;',
    '>': '&gt;',
    '"': '&quot;',
    '{': '&#123;',
    '}': '&#125;',
    '@': '&#64;',
  };

  return value.replace(/[&<>"{}@]/g, (character) => entities[character]);
}

/**
 * The `mat-stepper` template. Each step carries three section marker pairs,
 * one per `uses.slot` of its children (`header`, `children` for `content`,
 * `actions`), followed by the navigation buttons. The last step finishes the
 * stepper only when the node declares `produces.complete`.
 */
export function stepperTemplate(options: StepperAstOptions): string {
  const lastIndex = options.steps.length - 1;
  const steps = options.steps.map((step, index) => {
    const buttons = [
      ...(index > 0
        ? ['      <button mat-button type="button" matStepperPrevious>Back</button>']
        : []),
      ...(index < lastIndex
        ? ['      <button mat-button type="button" matStepperNext>Next</button>']
        : options.complete
          ? ['      <button mat-flat-button type="button" (click)="finish()">Finish</button>']
          : []),
    ];
    const optional = step.optional ? ' [optional]="true"' : '';

    return `  <mat-step label="${escapeAttributeText(step.label)}"${optional}>
    <header>
${templateSectionMarkers(stepSection(step, 'header'), '      ')}
    </header>
${templateSectionMarkers(stepSection(step, 'children'), '    ')}
    <footer>
${templateSectionMarkers(stepSection(step, 'actions'), '      ')}
${buttons.join('\n')}
    </footer>
  </mat-step>`;
  });

  return `<mat-stepper
  [linear]="linear()"
  [orientation]="orientation()"
  [selectedIndex]="selectedIndex()"
  (selectionChange)="onSelectionChange($event)"
>
${steps.join('\n')}
</mat-stepper>
`;
}

/** Component stylesheet; plain CSS, valid in every style language the project uses. */
export function stepperStylesheet(): string {
  return `:host {
  display: block;
}

footer {
  display: flex;
  flex-wrap: wrap;
  gap: 8px;
  margin-block-start: 16px;
}
`;
}

/**
 * Edit the component generated by `generateComponent` (standalone, OnPush,
 * with the begin/end section markers): import the Material stepper, declare the
 * inputs and outputs the node describes, and add the event handlers.
 *
 * @throws SchematicsException when the generated source lacks the section markers.
 */
export function stepperComponentSource(content: string, options: StepperAstOptions): string {
  let result = addNamedImports(withOnPush(content), '@angular/core', [
    'ChangeDetectionStrategy',
    'input',
    'model',
    ...(options.selectionChange || options.complete ? ['output'] : []),
  ]);
  result = addNamedImports(result, '@angular/cdk/stepper', [
    'StepperOrientation',
    'StepperSelectionEvent',
  ]);
  result = addNamedImports(result, '@angular/material/button', ['MatButtonModule']);
  result = addNamedImports(result, '@angular/material/stepper', ['MatStepperModule']);
  result = addToImportsArray(result, ['MatButtonModule', 'MatStepperModule']);

  result = insertBeforeMarker(
    result,
    '  // End input signals section',
    [
      `  readonly selectedIndex = model(${options.selectedIndex});`,
      `  readonly linear = input(${options.linear});`,
      `  readonly orientation = input<StepperOrientation>('${options.orientation}');`,
    ].join('\n'),
  );

  const outputs = [
    ...(options.selectionChange
      ? ['  readonly selectionChange = output<StepperSelectionEvent>();']
      : []),
    ...(options.complete ? ['  readonly complete = output<void>();'] : []),
  ];
  if (outputs.length > 0) {
    result = insertBeforeMarker(result, '  // End output signals section', outputs.join('\n'));
  }

  const methods = [
    '  protected onSelectionChange(event: StepperSelectionEvent): void {',
    '    this.selectedIndex.set(event.selectedIndex);',
    ...(options.selectionChange ? ['    this.selectionChange.emit(event);'] : []),
    '  }',
    ...(options.complete
      ? ['', '  protected finish(): void {', '    this.complete.emit();', '  }']
      : []),
  ];

  return insertBeforeClassClose(result, methods.join('\n'));
}

/**
 * Make the OnPush change detection explicit in the `@Component` decorator.
 * Angular 22 omits it from generated components because OnPush is its default.
 */
function withOnPush(content: string): string {
  if (/changeDetection\s*:/.test(content)) {
    return content;
  }

  return content.replace(
    /(@Component\(\{[\s\S]*?),?\n\}\)/,
    (_match, body: string) => `${body},\n  changeDetection: ChangeDetectionStrategy.OnPush,\n})`,
  );
}

/** Merge `names` into the import from `moduleSpecifier`, or add the import statement. */
function addNamedImports(content: string, moduleSpecifier: string, names: string[]): string {
  const existing = new RegExp(
    `import\\s*\\{([^}]*)\\}\\s*from\\s*'${escapeRegExp(moduleSpecifier)}';`,
  );
  const match = existing.exec(content);
  if (match) {
    const present = match[1]
      .split(',')
      .map((name) => name.trim())
      .filter(Boolean);
    const merged = [...present, ...names.filter((name) => !present.includes(name))].sort((a, b) =>
      a.toLowerCase().localeCompare(b.toLowerCase(), 'en'),
    );

    const statement = `import { ${merged.join(', ')} } from '${moduleSpecifier}';`;

    return content.replace(match[0], () => statement);
  }

  return insertBeforeMarker(
    content,
    '// End import section',
    `import { ${names.join(', ')} } from '${moduleSpecifier}';`,
  );
}

function addToImportsArray(content: string, classNames: string[]): string {
  const importsArray = /imports:\s*\[([^\]]*)\]/;
  const match = importsArray.exec(content);
  if (!match) {
    throw new SchematicsException('The generated component has no imports array to extend.');
  }
  const items = match[1]
    .split(',')
    .map((item) => item.trim())
    .filter(Boolean);
  const merged = [...items, ...classNames.filter((name) => !items.includes(name))];

  return content.replace(importsArray, () => `imports: [${merged.join(', ')}]`);
}

function insertBeforeMarker(content: string, marker: string, text: string): string {
  if (!content.includes(marker)) {
    throw new SchematicsException(
      `The generated component has no "${marker.trim()}" marker; it cannot be extended.`,
    );
  }

  return content.replace(marker, () => `${text}\n${marker}`);
}

function insertBeforeClassClose(content: string, text: string): string {
  const closingIndex = content.lastIndexOf('}');
  if (closingIndex === -1) {
    throw new SchematicsException('The generated component has no class body to extend.');
  }

  return `${content.slice(0, closingIndex).replace(/\s*$/, '')}\n\n${text}\n${content.slice(closingIndex)}`;
}

function escapeRegExp(value: string): string {
  return value.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}
