import { strings } from '@angular-devkit/core';

import { escapeTemplateText } from '../component/ast';
import { templateSectionMarkers } from '../embed-component/index';
import type { DialogAstOptions } from './ast';

/** Names that decide the identity of one generated dialog component. */
export interface DialogSourceNames {
  /** Kebab-case dialog name. */
  readonly name: string;
  /** Component class generated by Angular's `component` schematic. */
  readonly className: string;
  /** Component selector generated by Angular's `component` schematic. */
  readonly selector: string;
  /** Style file reference of the generated component, when it has one. */
  readonly styleUrl: string | undefined;
}

/** Template reference name of the dialog content. */
const CONTENT_TEMPLATE = 'dialogTemplate';

/** Element id the dialog is described by (`aria-describedby`). */
export function dialogContentId(name: string): string {
  return `${name}-content`;
}

/**
 * Template of a dialog component: the dialog content sits in an `ng-template`
 * that the component opens with `MatDialog`. The three regions keep the
 * `header`, `children` and `actions` section markers of the `component`
 * composition, so embedded children and `embed-component --slot` land inside the
 * dialog.
 */
export function dialogTemplate(name: string, options: DialogAstOptions): string {
  const title =
    options.title === undefined
      ? ''
      : `  <h2 mat-dialog-title>${escapeTemplateText(options.title)}</h2>\n`;
  const header = options.hasTitleRegion
    ? `${title}${templateSectionMarkers('header', '  ')}\n`
    : '';
  const actions = options.hasActionsRegion
    ? `  <mat-dialog-actions>\n${templateSectionMarkers('actions', '    ')}\n  </mat-dialog-actions>\n`
    : '';

  return `<ng-template #${CONTENT_TEMPLATE}>
${header}  <mat-dialog-content id="${dialogContentId(name)}">
${templateSectionMarkers('children', '    ')}
  </mat-dialog-content>
${actions}</ng-template>
`;
}

/**
 * Source of a dialog component. It keeps the begin/end section markers of the
 * `component` schematic so that `embed-component` can wire children into it.
 */
export function dialogComponentSource(names: DialogSourceNames, options: DialogAstOptions): string {
  const emits = options.close || options.cancel;
  const coreImports = [
    'ChangeDetectionStrategy',
    'Component',
    'DestroyRef',
    'effect',
    'inject',
    'input',
    'model',
    ...(emits ? ['output'] : []),
    'untracked',
    'viewChild',
  ];
  const materialImports = ['MatDialog', 'MatDialogModule'].concat(emits ? ['MatDialogState'] : []);
  const styleUrl = names.styleUrl === undefined ? '' : `  styleUrl: '${names.styleUrl}',\n`;
  const outputs = [
    ...(options.close
      ? [
          '  /** `produces.close`: emitted when the dialog closes without being dismissed. */',
          '  readonly closed = output<void>();',
        ]
      : []),
    ...(options.cancel
      ? [
          '  /** `produces.cancel`: emitted when Escape or a backdrop click dismisses the dialog. */',
          '  readonly cancelled = output<void>();',
        ]
      : []),
  ];
  const label = options.hasTitleRegion
    ? ''
    : `      // No title region: the dialog is named by its component name.
      ariaLabel: '${escapeSingleQuoted(strings.capitalize(strings.dasherize(names.name).replace(/-/g, ' ')))}',\n`;

  return `// Begin import section
import { ${coreImports.join(', ')} } from '@angular/core';
import type { TemplateRef } from '@angular/core';
import { ${materialImports.join(', ')} } from '@angular/material/dialog';
import type { MatDialogRef } from '@angular/material/dialog';
${emits ? "import { filter, merge } from 'rxjs';\n" : ''}// End import section

/**
 * Dialog public API (OpenUI \`widgets/dialog\`):
 * - \`open\` (\`uses.open\`): whether the dialog is shown; bind with \`[(open)]\`.
 * - \`modal\` (\`uses.modal\`): a modal dialog has a backdrop and sets \`aria-modal\`.
 * - Focus moves into the dialog and is contained until it closes, then returns to
 *   the element that had it; Escape dismisses the dialog.
 * - \`closed\` / \`cancelled\` (\`produces.close\` / \`produces.cancel\`): a dialog dismissed with
 *   Escape or a backdrop click emits \`cancelled\`; any other closing emits \`closed\`.
 * - Sections: header (title), children (content) and actions.
 */
@Component({
  selector: '${names.selector}',
  imports: [MatDialogModule],
  templateUrl: './${names.name}.html',
${styleUrl}  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class ${names.className} {
  // Begin injected services section
  private readonly dialog = inject(MatDialog);
  // End injected services section

  // Begin input signals section
  /** \`uses.open\`: whether the dialog is shown. */
  readonly open = model(${options.open});
  /** \`uses.modal\`: modal (backdrop, \`aria-modal\`) or non-modal. */
  readonly modal = input(${options.modal});
  // End input signals section

  // Begin output signals section
${outputs.map((line) => `${line}\n`).join('')}  // End output signals section

  private readonly template = viewChild.required<TemplateRef<unknown>>('${CONTENT_TEMPLATE}');
  private dialogRef: MatDialogRef<unknown> | null = null;

  constructor() {
    effect(() => {
      if (this.open()) {
        untracked(() => this.show());
      } else {
        untracked(() => this.dialogRef?.close());
      }
    });
    inject(DestroyRef).onDestroy(() => this.dialogRef?.close());
  }

  private show(): void {
    if (this.dialogRef) {
      return;
    }

    const modal = this.modal();
    const dialogRef = this.dialog.open(this.template(), {
${label}      ariaDescribedBy: '${dialogContentId(names.name)}',
      ariaModal: modal,
      hasBackdrop: modal,
    });
    this.dialogRef = dialogRef;
${emits ? dismissalTracking(options) : afterClosed('')}  }
}
`;
}

/** Tell a dismissal from any other closing, then emit the matching output. */
function dismissalTracking(options: DialogAstOptions): string {
  let emission: string;
  if (options.close && options.cancel) {
    emission = `      if (dismissed) {
        this.cancelled.emit();
      } else {
        this.closed.emit();
      }
`;
  } else if (options.cancel) {
    emission = `      if (dismissed) {
        this.cancelled.emit();
      }
`;
  } else {
    emission = `      if (!dismissed) {
        this.closed.emit();
      }
`;
  }

  return `
    // Material closes the dialog first, so its state tells a dismissal from a stray key.
    let dismissed = false;
    merge(
      dialogRef.backdropClick(),
      dialogRef.keydownEvents().pipe(filter((event) => event.key === 'Escape')),
    ).subscribe(() => {
      dismissed ||= dialogRef.getState() === MatDialogState.CLOSING;
    });
${afterClosed(emission)}`;
}

function afterClosed(emission: string): string {
  return `    dialogRef.afterClosed().subscribe(() => {
      this.dialogRef = null;
      this.open.set(false);
${emission}    });
`;
}

function escapeSingleQuoted(value: string): string {
  return value.replace(/\\/g, '\\\\').replace(/'/g, "\\'");
}
